package com.newer.medicine.domain;

/**
 * 角色枚举类
 */
public enum AuthorityName {
    ROLE_ADMIN,ROLE_ZDSCY,ROLE_FDCKY,ROLE_ZDCGY,ROLE_FDCGY,ROLE_YPGLY
    ,ROLE_ZJY,ROLE_ZDCW,ROLE_FDCWY,ROLE_FDCGJL,ROLE_ZDJL,ROLE_ZDCKGLY
    ,ROLE_FDPFSHY,ROLE_FDJL,ROLE_FDXSY
}
