package com.newer.medicine.domain;

public class ErpApply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_ID
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_NUMBER
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_NAME
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_BOSS
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyBoss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_ADR
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyAdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_PHONE
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_EMAIL
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private String applyEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.APPLY_ISVO
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private Short applyIsvo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_apply.ISVA
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    private Integer isva;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_ID
     *
     * @return the value of erp_apply.APPLY_ID
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_ID
     *
     * @param applyId the value for erp_apply.APPLY_ID
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_NUMBER
     *
     * @return the value of erp_apply.APPLY_NUMBER
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyNumber() {
        return applyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_NUMBER
     *
     * @param applyNumber the value for erp_apply.APPLY_NUMBER
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyNumber(String applyNumber) {
        this.applyNumber = applyNumber == null ? null : applyNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_NAME
     *
     * @return the value of erp_apply.APPLY_NAME
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyName() {
        return applyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_NAME
     *
     * @param applyName the value for erp_apply.APPLY_NAME
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyName(String applyName) {
        this.applyName = applyName == null ? null : applyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_BOSS
     *
     * @return the value of erp_apply.APPLY_BOSS
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyBoss() {
        return applyBoss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_BOSS
     *
     * @param applyBoss the value for erp_apply.APPLY_BOSS
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyBoss(String applyBoss) {
        this.applyBoss = applyBoss == null ? null : applyBoss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_ADR
     *
     * @return the value of erp_apply.APPLY_ADR
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyAdr() {
        return applyAdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_ADR
     *
     * @param applyAdr the value for erp_apply.APPLY_ADR
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyAdr(String applyAdr) {
        this.applyAdr = applyAdr == null ? null : applyAdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_PHONE
     *
     * @return the value of erp_apply.APPLY_PHONE
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyPhone() {
        return applyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_PHONE
     *
     * @param applyPhone the value for erp_apply.APPLY_PHONE
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyPhone(String applyPhone) {
        this.applyPhone = applyPhone == null ? null : applyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_EMAIL
     *
     * @return the value of erp_apply.APPLY_EMAIL
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public String getApplyEmail() {
        return applyEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_EMAIL
     *
     * @param applyEmail the value for erp_apply.APPLY_EMAIL
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyEmail(String applyEmail) {
        this.applyEmail = applyEmail == null ? null : applyEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.APPLY_ISVO
     *
     * @return the value of erp_apply.APPLY_ISVO
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public Short getApplyIsvo() {
        return applyIsvo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.APPLY_ISVO
     *
     * @param applyIsvo the value for erp_apply.APPLY_ISVO
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setApplyIsvo(Short applyIsvo) {
        this.applyIsvo = applyIsvo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_apply.ISVA
     *
     * @return the value of erp_apply.ISVA
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public Integer getIsva() {
        return isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_apply.ISVA
     *
     * @param isva the value for erp_apply.ISVA
     *
     * @mbg.generated Fri Jun 14 14:44:42 CST 2019
     */
    public void setIsva(Integer isva) {
        this.isva = isva;
    }
}