package com.newer.medicine.domain;

public class ErpPurchase {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_ID
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String purcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_SERIAL
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String purcSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_TITLE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String purcTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_NAME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String purcName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.STATE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_TIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String purcTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.CREATER
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.CREATETIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.ISVA
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private Integer isva;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_purchase.PURC_TOTAL_PRICE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    private Integer purcTotalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_ID
     *
     * @return the value of erp_purchase.PURC_ID
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getPurcId() {
        return purcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_ID
     *
     * @param purcId the value for erp_purchase.PURC_ID
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcId(String purcId) {
        this.purcId = purcId == null ? null : purcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_SERIAL
     *
     * @return the value of erp_purchase.PURC_SERIAL
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getPurcSerial() {
        return purcSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_SERIAL
     *
     * @param purcSerial the value for erp_purchase.PURC_SERIAL
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcSerial(String purcSerial) {
        this.purcSerial = purcSerial == null ? null : purcSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_TITLE
     *
     * @return the value of erp_purchase.PURC_TITLE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getPurcTitle() {
        return purcTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_TITLE
     *
     * @param purcTitle the value for erp_purchase.PURC_TITLE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcTitle(String purcTitle) {
        this.purcTitle = purcTitle == null ? null : purcTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_NAME
     *
     * @return the value of erp_purchase.PURC_NAME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getPurcName() {
        return purcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_NAME
     *
     * @param purcName the value for erp_purchase.PURC_NAME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcName(String purcName) {
        this.purcName = purcName == null ? null : purcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.STATE
     *
     * @return the value of erp_purchase.STATE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.STATE
     *
     * @param state the value for erp_purchase.STATE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_TIME
     *
     * @return the value of erp_purchase.PURC_TIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getPurcTime() {
        return purcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_TIME
     *
     * @param purcTime the value for erp_purchase.PURC_TIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcTime(String purcTime) {
        this.purcTime = purcTime == null ? null : purcTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.CREATER
     *
     * @return the value of erp_purchase.CREATER
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.CREATER
     *
     * @param creater the value for erp_purchase.CREATER
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.CREATETIME
     *
     * @return the value of erp_purchase.CREATETIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.CREATETIME
     *
     * @param createtime the value for erp_purchase.CREATETIME
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.ISVA
     *
     * @return the value of erp_purchase.ISVA
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public Integer getIsva() {
        return isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.ISVA
     *
     * @param isva the value for erp_purchase.ISVA
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setIsva(Integer isva) {
        this.isva = isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_purchase.PURC_TOTAL_PRICE
     *
     * @return the value of erp_purchase.PURC_TOTAL_PRICE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public Integer getPurcTotalPrice() {
        return purcTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_purchase.PURC_TOTAL_PRICE
     *
     * @param purcTotalPrice the value for erp_purchase.PURC_TOTAL_PRICE
     *
     * @mbg.generated Fri Jun 14 15:38:54 CST 2019
     */
    public void setPurcTotalPrice(Integer purcTotalPrice) {
        this.purcTotalPrice = purcTotalPrice;
    }
}