package com.newer.medicine.domain;

public class ErpPactType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.PATYPE_ID
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String patypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.PATYPE_SREIAL
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String patypeSreial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.PATYPE_NAME
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String patypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.REMARK
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.CRATENR
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String cratenr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.CREATER
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column erp_pact_type.ISVA
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    private Integer isva;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.PATYPE_ID
     *
     * @return the value of erp_pact_type.PATYPE_ID
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getPatypeId() {
        return patypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.PATYPE_ID
     *
     * @param patypeId the value for erp_pact_type.PATYPE_ID
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setPatypeId(String patypeId) {
        this.patypeId = patypeId == null ? null : patypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.PATYPE_SREIAL
     *
     * @return the value of erp_pact_type.PATYPE_SREIAL
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getPatypeSreial() {
        return patypeSreial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.PATYPE_SREIAL
     *
     * @param patypeSreial the value for erp_pact_type.PATYPE_SREIAL
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setPatypeSreial(String patypeSreial) {
        this.patypeSreial = patypeSreial == null ? null : patypeSreial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.PATYPE_NAME
     *
     * @return the value of erp_pact_type.PATYPE_NAME
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getPatypeName() {
        return patypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.PATYPE_NAME
     *
     * @param patypeName the value for erp_pact_type.PATYPE_NAME
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setPatypeName(String patypeName) {
        this.patypeName = patypeName == null ? null : patypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.REMARK
     *
     * @return the value of erp_pact_type.REMARK
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.REMARK
     *
     * @param remark the value for erp_pact_type.REMARK
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.CRATENR
     *
     * @return the value of erp_pact_type.CRATENR
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getCratenr() {
        return cratenr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.CRATENR
     *
     * @param cratenr the value for erp_pact_type.CRATENR
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setCratenr(String cratenr) {
        this.cratenr = cratenr == null ? null : cratenr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.CREATER
     *
     * @return the value of erp_pact_type.CREATER
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.CREATER
     *
     * @param creater the value for erp_pact_type.CREATER
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_pact_type.ISVA
     *
     * @return the value of erp_pact_type.ISVA
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public Integer getIsva() {
        return isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_pact_type.ISVA
     *
     * @param isva the value for erp_pact_type.ISVA
     *
     * @mbg.generated Fri Jun 14 15:19:48 CST 2019
     */
    public void setIsva(Integer isva) {
        this.isva = isva;
    }
}