package com.newer.medicine.domain;

import java.util.List;

public class ErpStaff {

    private String staId;
    private String depaId;
    private String annexId;
    private String staSerial;
    private String staName;
    private String staEmail;
    private String staPwd;
    private Short staAge;
    private String staSex;
    private String staEntrytime;
    private String staDimissiontime;
    private String staImg;
    private String staBackgd;
    private Integer isva;
    private String createtime;
    private String creater;
    private String remark;
    //部门名
    private String dname;
    //分店名
    private String annexName;
    //一个用户对应多个角色
    private List<Authority> authorities;

    public List<Authority> getAuthorities() {
        return authorities;
    }

    public void setAuthorities(List<Authority> authorities) {
        this.authorities = authorities;
    }

    public String getAnnexName() {
        return annexName;
    }

    public void setAnnexName(String annexName) {
        this.annexName = annexName;
    }

    public String getDname() {
        return dname;
    }

    public void setDname(String dname) {
        this.dname = dname;
    }

    public String getStaId() {
        return staId;
    }
    public void setStaId(String staId) {
        this.staId = staId == null ? null : staId.trim();
    }
    public String getDepaId() {
        return depaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.depa_id
     *
     * @param depaId the value for erp_staff.depa_id
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setDepaId(String depaId) {
        this.depaId = depaId == null ? null : depaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.ANNEX_ID
     *
     * @return the value of erp_staff.ANNEX_ID
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getAnnexId() {
        return annexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.ANNEX_ID
     *
     * @param annexId the value for erp_staff.ANNEX_ID
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setAnnexId(String annexId) {
        this.annexId = annexId == null ? null : annexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_serial
     *
     * @return the value of erp_staff.sta_serial
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaSerial() {
        return staSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_serial
     *
     * @param staSerial the value for erp_staff.sta_serial
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaSerial(String staSerial) {
        this.staSerial = staSerial == null ? null : staSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_name
     *
     * @return the value of erp_staff.sta_name
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaName() {
        return staName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_name
     *
     * @param staName the value for erp_staff.sta_name
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaName(String staName) {
        this.staName = staName == null ? null : staName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_email
     *
     * @return the value of erp_staff.sta_email
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaEmail() {
        return staEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_email
     *
     * @param staEmail the value for erp_staff.sta_email
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaEmail(String staEmail) {
        this.staEmail = staEmail == null ? null : staEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_pwd
     *
     * @return the value of erp_staff.sta_pwd
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaPwd() {
        return staPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_pwd
     *
     * @param staPwd the value for erp_staff.sta_pwd
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaPwd(String staPwd) {
        this.staPwd = staPwd == null ? null : staPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_age
     *
     * @return the value of erp_staff.sta_age
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public Short getStaAge() {
        return staAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_age
     *
     * @param staAge the value for erp_staff.sta_age
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaAge(Short staAge) {
        this.staAge = staAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_sex
     *
     * @return the value of erp_staff.sta_sex
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaSex() {
        return staSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_sex
     *
     * @param staSex the value for erp_staff.sta_sex
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaSex(String staSex) {
        this.staSex = staSex == null ? null : staSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_entryTime
     *
     * @return the value of erp_staff.sta_entryTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaEntrytime() {
        return staEntrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_entryTime
     *
     * @param staEntrytime the value for erp_staff.sta_entryTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaEntrytime(String staEntrytime) {
        this.staEntrytime = staEntrytime == null ? null : staEntrytime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_dimissionTime
     *
     * @return the value of erp_staff.sta_dimissionTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaDimissiontime() {
        return staDimissiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_dimissionTime
     *
     * @param staDimissiontime the value for erp_staff.sta_dimissionTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaDimissiontime(String staDimissiontime) {
        this.staDimissiontime = staDimissiontime == null ? null : staDimissiontime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_img
     *
     * @return the value of erp_staff.sta_img
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaImg() {
        return staImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_img
     *
     * @param staImg the value for erp_staff.sta_img
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaImg(String staImg) {
        this.staImg = staImg == null ? null : staImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.sta_backgd
     *
     * @return the value of erp_staff.sta_backgd
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getStaBackgd() {
        return staBackgd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.sta_backgd
     *
     * @param staBackgd the value for erp_staff.sta_backgd
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setStaBackgd(String staBackgd) {
        this.staBackgd = staBackgd == null ? null : staBackgd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.ISVA
     *
     * @return the value of erp_staff.ISVA
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public Integer getIsva() {
        return isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.ISVA
     *
     * @param isva the value for erp_staff.ISVA
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setIsva(Integer isva) {
        this.isva = isva;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.createTime
     *
     * @return the value of erp_staff.createTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.createTime
     *
     * @param createtime the value for erp_staff.createTime
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.creater
     *
     * @return the value of erp_staff.creater
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.creater
     *
     * @param creater the value for erp_staff.creater
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column erp_staff.remark
     *
     * @return the value of erp_staff.remark
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column erp_staff.remark
     *
     * @param remark the value for erp_staff.remark
     *
     * @mbg.generated Fri Jun 14 09:39:43 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}